export const SET_PLACES = "SET_PLACES";
export const REMOVE_PLACE = "REMOVE_PLACE";

export const TRY_AUTH = "TRY_AUTH";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";



export const LOGINREQUEST = 'LOGINREQUEST';
export const REQUESTSUCCESS = 'REQUESTSUCCESS';
export const REQUESTFAILED = 'REQUESTFAILED';


export const FETCH_MESSAGE = "FETCH_MESSAGE";
export const RECIEVED_MESSAGE = "RECIEVED_MESSAGE"
export const MESSAGE_READ= "MESSAGE_READ"

export const FETCH_REQUEST = "FETCH_REQUEST"
export const FETCH_REQUEST_SUCCESS = "FETCH_REQUEST_SUCCESS"
export const FETCH_REQUEST_FAIL = "FETCH_REQUEST_FAIL"

export const REFRESH_REQUEST = "REFRESH_REQUEST"
export const REFRESH_REQUEST_SUCCESS = "REFRESH_REQUEST_SUCCESS"
export const REFRESH_REQUEST_FAIL = "REFRESH_REQUEST_FAIL"